convert/objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Images__c</fullName>
        <formula>IMAGE( URL__c, Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

convert/classes/ProductController.cls
public with sharing class ProductController {
    

    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts() {
    
        return [SELECT Id, Name, Price__c, Images__c, URL__c FROM Product2 LIMIT 3];
    }
    
    
    @AuraEnabled
    public static void updateProductQuantity(Id productId, Integer newQuantity) {
        Product2 product = [SELECT Id, Quantity__c FROM Product2 WHERE Id = :productId];
        product.Quantity__c = newQuantity;
        update product;
    }   
}