convert/objects/StripeAPI__mdt.object
<CustomObject>
    <label>StripeAPI</label>
    <pluralLabel>StripeAPIS</pluralLabel>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret_key__c</fullName>
        <label>Secret key</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/stripeService.cls
public class stripeService {
    @AuraEnabled(cacheable=true)
    
    public static void createCharge(){
        StripeAPI__mdt stripeIntegration=[Select Secret_key__c,End_Point__c from StripeAPI__mdt];
        String result='fail';
        String stripeSecretKey = stripeIntegration.Secret_key__c;
        String endpoint = stripeIntegration.End_Point__c;
        
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setHeader('Authorization', 'Bearer ' + stripeSecretKey);
        request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        
        String requestBody = 'amount=10000&currency=usd&source=tok_visa_debit';
        request.setBody(requestBody);
        
        Http http = new Http();
        HTTPResponse response = http.send(request);
        
        if (response.getStatusCode() == 200) {
            System.debug('Gaurav Dubey: ' + response.getBody());
            System.debug(response.getStatusCode());
        } else {
            System.debug('Error: ' + response.getBody());
            System.debug(response.getStatusCode());
        }
    }
    
    
    
}